version: "3.8"
services:
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    links:
      - backend
    networks:
      - idp_network
  
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend-docker
    restart: always
    depends_on:
      - db
    links:
      - db
    networks:
      - idp_network
  
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IDP_db
    ports:
      - "3307:3306"
    container_name: database
    restart: always
    networks:
      - idp_network

networks:
  idp_network:  



