version: "3.8"
services:
  frontend:
    image: hypersmoit/idp_frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - idp_network
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first
  
  backend:
    image: hypersmoit/idp_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - idp_network
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        order: start-first
      rollback_config:
        parallelism: 2
        order: stop-first
  
  db:
    image: hypersmoit/idp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IDP_db
    ports:
      - "3307:3306"
    networks:
      - idp_network
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  
  kong:
    image: kong:latest
    volumes:
      - ./Kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off' 
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - idp_network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3001:3000
    depends_on:
      - prometheus
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - idp_network
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - idp_network

volumes:
  grafana-volume:

networks:
  idp_network:  



